# fly.toml app configuration file generated for rss-demo on 2024-11-07T16:44:32+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rss-demo'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
